// src/routes/projects/bingo-caller/+page.svelte
<script lang="ts">
  import SEO from '$components/SEO.svelte';
  import ProjectIcons from '$components/ProjectIcons.svelte';
  import ProjectBtnLink from '$components/ProjectBtnLink.svelte';
  let icons = ['jQuery', 'Sass', 'GitHub'];
</script>

<SEO title="Bingo Caller" hideHeader />

<h1>Bingo Caller</h1>

<p>
  This project was initially inspired from an activity where I helped run a bingo game. One person
  called out the numbers, and I wrote the numbers called in a word document that was projected for
  everyone to see. As I ran the word document, I realized that there was a better way to do it where
  it would only need one person to manage the game. I decided to make my own system.
</p>

<p>
  There are several different bingo callers out there, however this one is free to use, free of ads,
  and there is no personal information that you need to give in order to use it. To me, I feel like
  these are enough reasons to use a website like this. Bingo Caller also comes with an adjustable
  timer. You can set it to call a new number every set number of seconds. If you do that, then
  everyone can have the chance to play. As for the branding, I didn’t spend a lot of time on it, but
  I thought it still turned out pretty good. I went with the font Pacifico. I added a little wave to
  the font, and really liked it. As for the color, purple seemed to do the trick.
</p>

<enhanced:img src="$img/projects/bingo-caller/bingo-caller.jpg" alt="Website Screenshot" />

<ProjectBtnLink href="https://bingo.nathanblaylock.com" />

<p>
  I have had a few people use my bingo caller, and am glad that they enjoy using it. I have a few
  ideas in the future, such as adding audio, and maybe adding in some auto generated cards that the
  user can print off.
</p>

<!-- <ProjectIcons {icons} /> -->

// pages/projects/bingo-caller.vue
<template>
  <div class="pb-5">
    <Seo
      title="Bingo Caller Portfolio"
      description='Check out my "Just For Fun" project I created; a Bingo Caller to help groups play a game with minimal materials and setup'
      img="/img/projects/bingo/bingo-screenshot.png"
    />
    <img src="/img/projects/bingo/bingo-hero.png" class="img-fluid" alt="" />
    <div class="container-sm">
      <h1>
        Bingo Caller
      </h1>
      <p>
        This project was initially inspired from an activity where I helped run
        a bingo game. One person called out the numbers, and I wrote the numbers
        called in a word document that was projected for everyone to see. As I
        ran the word document, I realized that there was a better way to do it
        where it would only need one person to manage the game. I decided to
        make my own system.
      </p>
      <p>
        There are several different bingo callers out there, however this one is
        free to use, free of ads, and there is no personal information that you
        need to give in order to use it. To me, I feel like these are enough
        reasons to use a program like this. Bingo Caller also comes with an
        adjustable timer. You can set it to call a new number every set number
        of seconds. If you do that, then everyone can have the chance to play.
      </p>
      <p>
        As for the branding, I didn’t spend a lot of time on it, but I thought
        it still turned out pretty good. I went with the font Pacifico. I added
        a little wave to the font, and really liked it. As for the color, purple
        seemed to do the trick.
      </p>
      <ProjectImg src="/img/projects/bingo/bingo-screenshot.png" />
      <p class="text-center">
        <a
          href="https://bingo.nathanblaylock.com"
          class="btn btn-primary"
          target="_blank"
          >Visit Bingo Caller</a
        >
      </p>
      <p>
        I have had a few people use my bingo caller, and am glad that they enjoy
        using it. I have a few ideas in the future, such as adding audio, and
        maybe adding in some auto generated cards that the user can print off.
      </p>
    </div>
  </div>
</template>
