// components/Footer.vue
<template>
  <footer class="mt-3 mt-sm-4 mt-md-5">
    <b-container
      class="
        border-top border-gray
        d-flex
        align-items-center
        justify-content-between
        py-3
      "
    >
      <ul class="list-unstyled d-flex flex-wrap mb-0">
        <li>&copy; Nathan Blaylock {{ year }}</li>
        <li>
          <a href="https://docs.nathanblaylock.com" target="_blank"
            >Documentation</a
          >
        </li>
        <li>
          <a href="https://github.com/ngblaylock" target="_blank">GitHub</a>
        </li>
        <li>
          <a href="https://dev.to/ngblaylock" target="_blank">Dev.to Blog</a>
        </li>
        <li>
          <a href="/privacy">Privacy</a>
        </li>
      </ul>
      <div class="logos">
        <a
          class="uxc"
          href="https://www.nngroup.com/ux-certification/verify/"
          target="_blank"
          ><img
            src="https://media.nngroup.com/nng-uxc-badge.png"
            alt="UX Certification Badge from Nielsen Norman Group"
        /></a>
        <img class="logo" src="/img/logo-red.svg" alt="NB Logo" />
      </div>
    </b-container>
  </footer>
</template>

<script>
export default {
  data() {
    return {
      year: new Date().getFullYear(),
    }
  },
}
</script>

<style lang="scss" scoped>
li {
  display: block;
  padding: 0 12px 0 0;
}
.uxc {
  display: inline-block;
  margin-left: auto;
  img {
    max-height: 110px;
  }
}
.logos {
  display: flex;
  justify-content: center;
  align-items: center;
}
.logo {
  max-height: 50px;
  margin-left: 12px;
}
@include media-breakpoint-down(md) {
  .logos {
    .uxc img {
      max-height: 80px;
    }
    .logo {
      max-height: 40px;
    }
  }
}
@include media-breakpoint-down(sm) {
  li {
    width: 100%;
  }
}
</style>

// src/lib/components/Footer.svelte
<script lang="ts">
  import { themeSwitcher } from '@ngblaylock/bootstrap-extensions';
  if (import.meta.hot) {
    import.meta.hot.accept(() => {
      themeSwitcher.initTheme();
    });
  }
</script>

<div class="container">
  <footer class="border-top hstack flex-wrap gap-3 justify-content-center py-3">
    <div>© Nathan Blaylock {new Date().getFullYear()}</div>

    <div class="hstack flex-wrap gap-3 justify-content-center">
      <a href="https://docs.nathanblaylock.com/" target="_blank">Documentation</a>
      <a href="https://github.com/ngblaylock" target="_blank">GitHub</a>
      <a href="https://dev.to/ngblaylock" target="_blank">Dev.to Blog</a>
      <a href="/privacy">Privacy</a>
      <input type="checkbox" aria-label="Switch Theme" class="theme-switch" data-bse-theme-switch />
    </div>

    <div class="hstack gap-2 ms-lg-auto">
      <a href="https://www.nngroup.com/ux-certification/verify/" target="_blank"
        ><img
          src="https://media.nngroup.com/nng-uxc-badge.png"
          alt="UX Certified, Nielsen/Norman Group"
          class="uxc"
        /></a
      >
      <div class="logo">
        <svg
          width="271"
          height="185"
          viewBox="0 0 271 185"
          fill="red"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M244.315 158.873C238.31 165.152 228.483 168.427 214.561 168.427H164.333V96.9072H205.825C237.218 96.9072 253.051 109.464 253.051 134.578C253.051 144.405 250.048 152.322 244.315 158.873ZM164.333 16.6517H208.828C233.942 16.6517 246.499 27.0248 246.499 47.7711C246.499 57.8713 242.677 66.0607 235.307 72.0662C227.937 78.0717 217.017 80.8015 202.55 80.8015H164.333V16.6517ZM145.77 168.154H130.756V16.6517H145.77V168.154ZM260.421 103.186C253.869 95.2693 245.134 90.0827 234.488 87.3529C243.496 84.0772 250.594 78.8906 255.78 72.0662C260.967 65.2417 263.697 57.3254 263.697 48.0441C263.697 34.3952 259.329 22.9301 250.321 13.6489C241.312 4.64063 227.118 0 207.19 0H112.194V91.4476L56.2335 0H37.398L112.194 124.478V152.868C110.01 148.773 18.8355 0 18.8355 0H0V184.806H18.5625V34.1222C19.1085 34.9412 111.921 184.806 111.921 184.806H211.285C232.031 184.806 247.045 179.892 256.326 169.792C265.608 159.692 270.248 147.681 270.248 133.213C270.248 120.929 266.972 111.102 260.421 103.186Z"
          />
        </svg>
      </div>
    </div>
  </footer>
</div>

<style lang="scss">
  .uxc {
    max-height: 100px;
    margin: 0;
  }
  .logo svg {
    max-height: 50px;
    width: auto;
    fill: $primary;
    :global([data-bs-theme='dark']) & {
      fill: var(--bse-base-i1);
    }
  }
</style>
